---
app:
  # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600
    
  # Trellis
  trellis:
    enabled: true
    endpoint: http://localhost:80
    authentication:
      enabled: false
      username: admin
      password: admin
  # Wikibase
  wikibase:
    enabled: false
    api: 
      url: http://localhost:8181/api.php
      username: WikibaseAdmin
      password: WikibaseDockerAdminPass
    query:
      default-language: es
    site:
      uri: http://localhost:8181/entity/  

  # Swagger
  swagger:
    enabled: false
    
  # factory uris  
  generator-uris:
    endpoint: http://localhost:9326
    endpoint-link-uri: ${app.generator-uris.endpoint}/uri-factory/local
    endpoint-local-resource-storage-uri: ${app.generator-uris.endpoint}/uri-factory/local/resource
    endpoint-local-property-storage-uri: ${app.generator-uris.endpoint}/uri-factory/local/property
    endpoint-property: ${app.generator-uris.endpoint}/uri-factory/canonical/property
  # delta  
  delta:
    mockup-file-path: C:\\tmp\\input.json
    
## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9321
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false
## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}      
