FROM stain/jena-fuseki:latest
COPY ./fuseki-conf/config.ttl /fuseki/config.ttl
COPY ./fuseki-conf/shiro.ini /jena-fuseki/shiro.ini
COPY ./fuseki-conf/shiro.ini /fuseki/shiro.ini
COPY ./fuseki-conf/log4j.properties /fuseki/log4j.properties
COPY ./fuseki-conf/fuseki-server /jena-fuseki/fuseki-server
COPY ./fuseki-conf/jena-permissions-poc-1.0-SNAPSHOT.jar /fuseki/jena-permissions-poc-1.0-SNAPSHOT.jar

